### ISSUE TITLE
Can't load CD images if their filenames have Unicode characters

### ISSUE THREAD

**Issue by PeladoFeo** [VARCem/VARCem#64] opened 2018-12-23 15:04 UTC
However, I can use floppy images with Unicode characters in their filenames perfectly.

**Comment by waltje** [comment] 2018-12-23 18:14
Confirmed, will be fixed.  Thanks!

--fred

--------------------------------------------
On Sun, 12/23/18, PeladoFeo <notifications@github.com> wrote:

 Subject: [VARCem/VARCem] Can't load CD images if their names have Unicode characters (#64)
 To: "VARCem/VARCem" <VARCem@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Sunday, December 23, 2018, 10:04 AM
 
 Title says it all.
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view it on
 GitHub, or mute
 the thread.

**Comment by waltje** [comment] 2019-03-06 04:44
Fixed in #347, thanks for reporting.

**Closed by waltje** 2019-03-06 04:44 UTC
